// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeServer(apiKey2 string) Server {
	mainWeatherService := NewWeatherServiceWire(apiKey2)
	mainServer := NewServerWire(mainWeatherService)
	return mainServer
}
